version: "3.9"

services:
  ingestion:
    image: ingest-service:latest
    build: ./ingestion
    container_name: ingestion
    ports:
      - "8080:8080"
    environment:
      PROCESSOR_URL: "http://process:8081/process"
    depends_on:
      - process

  process:
    image: process-service:latest
    build: ./process
    container_name: process
    ports:
      - "8081:8081"
