apiVersion: v1
kind: Service
metadata: 
  name: ingestion
  namespace: doc-processing
spec:
  type: NodePort
  selector:
    app: ingestion
  ports: 
    - port: 8080
      targetPort: 8080
      nodePort: 30080 